name: Fractals
favicon: null
layout_spectrum: 0.7561791206244379
typography_spectrum: 0.4853688469156623
title: Fractal Testings
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4ea03'
    - '#79007e'
    - '#4e509a'
    - '#ed8e4a'
    - '#1e0c00'
  brandStrength: 0
  lightness: 0.7656244887039065
  saturation: 0.07567382766865194
  rhythmicContrast: 0.9009594658855349
purpose: []
